INSERT INTO ISD_code(country,country_code,isd) VALUES ('Afghanistan','AF','+93');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Albania','AL','+355');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Algeria','DZ','+213');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('American Samoa','AS','+1-684');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Andorra Principality of','AD','+376');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Angola','AO','+244');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Anguilla','AI','+1-264');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Antarctica','AQ','+672');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Antigua and Barbuda','AG','+1-268');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Argentina','AR','+54');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Armenia','AM','+374');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Aruba','AW','+297');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Australia','AU','+61');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Austria','AT','+43');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Azerbaijan or Azerbaidjan (Former Azerbaijan Soviet Socialist Republic)','AZ','+994');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Bahamas','Commonwealth of The','BS');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Bahrain','Kingdom of (Former Dilmun)','BH');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Bangladesh (Former East Pakistan)','BD','+880');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Barbados','BB','+1-246');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Belarus (Former Belorussian [Byelorussian] Soviet Socialist Republic)','BY','+375');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Belgium','BE','+32');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Belize (Former British Honduras)','BZ','+501');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Benin (Former Dahomey)','BJ','+229');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Bermuda','BM','+1-441');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Bhutan','Kingdom of','BT');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Bolivia','BO','+591');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Bosnia and Herzegovina','BA','+387');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Botswana (Former Bechuanaland)','BW','+267');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Bouvet Island (Territory of Norway)','BV',NULL);
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Brazil','BR','+55');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('British Indian Ocean Territory (BIOT)','IO',NULL);
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Brunei (Negara Brunei Darussalam)','BN','+673');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Bulgaria','BG','+359');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Burkina Faso (Former Upper Volta)','BF','+226');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Burundi (Former Urundi)','BI','+257');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Cambodia','Kingdom of (Former Khmer Republic','Kampuchea Republic)');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Cameroon (Former French Cameroon)','CM','+237');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Canada','CA','+1');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Cape Verde','CV','+238');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Cayman Islands','KY','+1-345');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Central African Republic','CF','+236');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Chad','TD','+235');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Chile','CL','+56');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('China','CN','+86');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Christmas Island','CX','+53');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Cocos (Keeling) Islands','CC','+61');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Colombia','CO','+57');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Cook Islands (Former Harvey Islands)','CK','+682');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Costa Rica','CR','+506');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Cote D''Ivoire (Former Ivory Coast)','CI','+225');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Croatia (Hrvatska)','HR','+385');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Cuba','CU','+53');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Cyprus','CY','+357');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Czech Republic','CZ','+420');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Denmark','DK','+45');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Djibouti (Former French Territory of the Afars and Issas','French Somaliland)','DJ');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Dominica','DM','+1-767');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Dominican Republic','DO','+1-809 and +1-829');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('East Timor (Former Portuguese Timor)','TP','+670');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Ecuador','EC','+593');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Egypt (Former United Arab Republic - with Syria)','EG','+20');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('El Salvador','SV','+503');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Equatorial Guinea (Former Spanish Guinea)','GQ','+240');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Eritrea (Former Eritrea Autonomous Region in Ethiopia)','ER','+291');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Estonia (Former Estonian Soviet Socialist Republic)','EE','+372');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Ethiopia (Former Abyssinia','Italian East Africa)','ET');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Falkland Islands (Islas Malvinas)','FK','+500');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Faroe Islands','FO','+298');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Fiji','FJ','+679');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Finland','FI','+358');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('France','FR','+33');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('French Guiana or French Guyana','GF','+594');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('French Polynesia (Former French Colony of Oceania)','PF','+689');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('French Southern Territories and Antarctic Lands','TF',NULL);
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Gabon (Gabonese Republic)','GA','+241');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Gambia','The','GM');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Georgia (Former Georgian Soviet Socialist Republic)','GE','+995');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Germany','DE','+49');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Ghana (Former Gold Coast)','GH','+233');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Gibraltar','GI','+350');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Great Britain (United Kingdom)','GB',NULL);
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Greece','GR','+30');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Greenland','GL','+299');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Grenada','GD','+1-473');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Guadeloupe','GP','+590');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Guam','GU','+1-671');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Guatemala','GT','+502');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Guinea (Former French Guinea)','GN','+224');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Guinea-Bissau (Former Portuguese Guinea)','GW','+245');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Guyana (Former British Guiana)','GY','+592');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Haiti','HT','+509');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Honduras','HN','+504');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Hong Kong','HK','+852');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Hungary','HU','+36');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Iceland','IS','+354');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('India','IN','+91');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Indonesia (Former Netherlands East Indies; Dutch East Indies)','ID','+62');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Iran Islamic Republic of','IR','+98');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Iraq','IQ','+964');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Ireland','IE','+353');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Israel','IL','+972');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Italy','IT','+39');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Jamaica','JM','+1-876');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Japan','JP','+81');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Jordan (Former Transjordan)','JO','+962');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Kazakstan or Kazakhstan (Former Kazakh Soviet Socialist Republic)','KZ','+7');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Kenya (Former British East Africa)','KE','+254');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Kiribati (Pronounced keer-ree-bahss) (Former Gilbert Islands)','KI','+686');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Korea Democratic People''s Republic of (North Korea)','KP','+850');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Korea Republic of (South Korea)','KR','+82');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Kuwait','KW','+965');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Kyrgyzstan (Kyrgyz Republic) (Former Kirghiz Soviet Socialist Republic)','KG','+996');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Lao People''s Democratic Republic (Laos)','LA','+856');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Latvia (Former Latvian Soviet Socialist Republic)','LV','+371');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Lebanon','LB','+961');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Lesotho (Former Basutoland)','LS','+266');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Liberia','LR','+231');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Libya (Libyan Arab Jamahiriya)','LY','+218');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Liechtenstein','LI','+423');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Lithuania (Former Lithuanian Soviet Socialist Republic)','LT','+370');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Luxembourg','LU','+352');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Macau','MO','+853');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Macedonia The Former Yugoslav Republic of','MK','+389');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Madagascar (Former Malagasy Republic)','MG','+261');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Malawi (Former British Central African Protectorate','Nyasaland)','MW');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Malaysia','MY','+60');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Maldives','MV','+960');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Mali (Former French Sudan and Sudanese Republic)','ML','+223');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Malta','MT','+356');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Marshall Islands (Former Marshall Islands District - Trust Territory of the Pacific Islands)','MH','+692');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Martinique (French)','MQ','+596');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Mauritania','MR','+222');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Mauritius','MU','+230');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Mayotte (Territorial Collectivity of Mayotte)','YT','+269');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Mexico','MX','+52');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Micronesia','Federated States of (Former Ponape','Truk');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Moldova','Republic of','MD');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Monaco','Principality of','MC');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Mongolia (Former Outer Mongolia)','MN','+976');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Montserrat','MS','+1-664');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Morocco','MA','+212');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Mozambique (Former Portuguese East Africa)','MZ','+258');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Myanmar','Union of (Former Burma)','MM');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Namibia (Former German Southwest Africa','South-West Africa)','NA');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Nauru (Former Pleasant Island)','NR','+674');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Nepal','NP','+977');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Netherlands','NL','+31');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Netherlands Antilles (Former Curacao and Dependencies)','AN','+599');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('New Caledonia','NC','+687');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('New Zealand (Aotearoa)','NZ','+64');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Nicaragua','NI','+505');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Niger','NE','+227');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Nigeria','NG','+234');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Niue (Former Savage Island)','NU','+683');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Norfolk Island','NF','+672');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Northern Mariana Islands (Former Mariana Islands District - Trust Territory of the Pacific Islands)','MP','+1-670');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Norway','NO','+47');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Oman','Sultanate of (Former Muscat and Oman)','OM');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Pakistan (Former West Pakistan)','PK','+92');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Palau (Former Palau District - Trust Terriroty of the Pacific Islands)','PW','+680');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Palestinian State (Proposed)','PS','+970');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Panama','PA','+507');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Papua New Guinea (Former Territory of Papua and New Guinea)','PG','+675');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Paraguay','PY','+595');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Peru','PE','+51');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Philippines','PH','+63');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Pitcairn Island','PN',NULL);
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Poland','PL','+48');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Portugal','PT','+351');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Puerto Rico','PR','+1-787 or +1-939');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Qatar','State of','QA');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Reunion (French) (Former Bourbon Island)','RE','+262');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Romania','RO','+40');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Russia - USSR (Former Russian Empire','Union of Soviet Socialist Republics','Russian Soviet Federative Socialist Republic) Now RU - Russian Federation');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Russian Federation','RU','+7');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Rwanda (Rwandese Republic) (Former Ruanda)','RW','+250');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Saint Helena','SH','+290');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Saint Kitts and Nevis (Former Federation of Saint Christopher and Nevis)','KN','+1-869');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Saint Lucia','LC','+1-758');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Saint Pierre and Miquelon','PM','+508');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Saint Vincent and the Grenadines','VC','+1-784');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Samoa (Former Western Samoa)','WS','+685');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('San Marino','SM','+378');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Sao Tome and Principe','ST','+239');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Saudi Arabia','SA','+966');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Serbia','Republic of','RS');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Senegal','SN','+221');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Seychelles','SC','+248');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Sierra Leone','SL','+232');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Singapore','SG','+65');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Slovakia','SK','+421');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Slovenia','SI','+386');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Solomon Islands (Former British Solomon Islands)','SB','+677');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Somalia (Former Somali Republic','Somali Democratic Republic)','SO');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('South Africa (Former Union of South Africa)','ZA','+27');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Spain','ES','+34');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Sri Lanka (Former Serendib','Ceylon)','LK');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Sudan (Former Anglo-Egyptian Sudan)','SD','+249');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Suriname (Former Netherlands Guiana','Dutch Guiana)','SR');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Svalbard (Spitzbergen) and Jan Mayen Islands','SJ',NULL);
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Swaziland Kingdom of','SZ','+268');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Sweden','SE','+46');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Switzerland','CH','+41');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Syria (Syrian Arab Republic) (Former United Arab Republic - with Egypt)','SY','+963');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Taiwan (Former Formosa)','TW','+886');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Tajikistan (Former Tajik Soviet Socialist Republic)','TJ','+992');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Tanzania United Republic of (Former United Republic of Tanganyika and Zanzibar)','TZ','+255');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Thailand (Former Siam)','TH','+66');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Tokelau','TK','+690');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Tonga Kingdom of (Former Friendly Islands)','TO','+676');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Trinidad and Tobago','TT','+1-868');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Tromelin Island','TE',NULL);
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Tunisia','TN','+216');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Turkey','TR','+90');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Turkmenistan (Former Turkmen Soviet Socialist Republic)','TM','+993');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Turks and Caicos Islands','TC','+1-649');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Tuvalu (Former Ellice Islands)','TV','+688');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Uganda','UG','+256');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Ukraine (Former Ukrainian National Republic','Ukrainian State','Ukrainian Soviet Socialist Republic)');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('United Arab Emirates (UAE) (Former Trucial Oman','Trucial States)','AE');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('United Kingdom (Great Britain / UK)','GB','+44');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('United States','US','+1');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('United States Minor Outlying Islands','UM',NULL);
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Uruguay','Oriental Republic of (Former Banda Oriental','Cisplatine Province)');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Uzbekistan (Former UZbek Soviet Socialist Republic)','UZ','+998');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Vanuatu (Former New Hebrides)','VU','+678');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Vatican City State (Holy See)','VA','+418');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Venezuela','VE','+58');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Vietnam','VN','+84');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Wallis and Futuna Islands','WF','+681');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Yemen','YE','+967');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Zambia','Republic of (Former Northern Rhodesia)','ZM');
INSERT INTO ISD_code(country,country_code,isd) VALUES ('Zimbabwe','Republic of (Former Southern Rhodesia','Rhodesia)');


